version: '2'
services:
  web:
    image: 474897046194.dkr.ecr.ap-southeast-1.amazonaws.com/webapp:latest
    ports:
      - "80:80"
    links:
      - db:mysql
    entrypoint: /docker-entrypoint.sh
  db:
    image: mysql:5.7
    volumes:
      - "/data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test